services:
  backend:
    build: ./backend
    container_name: mern-backend
    expose:
      - "5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mern-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
